source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'dotenv'
gem 'colorize'
gem 'syntax'
gem 'selenium-webdriver'
gem 'test-unit'
gem 'mime-types'
gem 'netrc'
gem 'http-cookie'
gem 'rest-client'
